FROM oven/bun:1
WORKDIR /app

# Declare build args so Railway env vars are passed to Vite at build time
ARG VITE_API_URL
ARG VITE_FIREBASE_API_KEY
ARG VITE_FIREBASE_AUTH_DOMAIN
ARG VITE_FIREBASE_PROJECT_ID
ARG VITE_FIREBASE_APP_ID
ARG VITE_FIREBASE_STORAGE_BUCKET
ARG VITE_FIREBASE_MESSAGING_SENDER_ID
ARG VITE_FRONTEND_URL

# Make them available to Vite build
ENV VITE_API_URL=$VITE_API_URL
ENV VITE_FIREBASE_API_KEY=$VITE_FIREBASE_API_KEY
ENV VITE_FIREBASE_AUTH_DOMAIN=$VITE_FIREBASE_AUTH_DOMAIN
ENV VITE_FIREBASE_PROJECT_ID=$VITE_FIREBASE_PROJECT_ID
ENV VITE_FIREBASE_APP_ID=$VITE_FIREBASE_APP_ID
ENV VITE_FIREBASE_STORAGE_BUCKET=$VITE_FIREBASE_STORAGE_BUCKET
ENV VITE_FIREBASE_MESSAGING_SENDER_ID=$VITE_FIREBASE_MESSAGING_SENDER_ID
ENV VITE_FRONTEND_URL=$VITE_FRONTEND_URL

# Copy everything
COPY . .

# Install deps and build
RUN cd packages/web && bun install
RUN cd packages/web && bun run build

# Set port
ENV PORT=10000
EXPOSE 10000

# Apply committed migrations before accepting traffic, then start the server.
CMD ["sh", "-c", "cd packages/web && bun run db:migrate:deploy && bun src/server.ts"]
