name: librepair
app_id: da_Ra7IetdUVkpy
owner: sonnietechnologyllc
package: sonnietechnologyllc/librepair@^0.1.24
domains:
- librepair.wasmer.app
kind: wasmer.io/App.v0
description: LIBrepair — On-Demand Auto Repair Platform
