kind: wasmer.io/App.v0
name: librepair
app_id: da_Ra7IetdUVkpy
owner: sonnietechnologyllc
package: sonnietechnologyllc/librepair@^0.1.25
domains:
- librepair.wasmer.app
description: LIBrepair — On-Demand Auto Repair Platform
