[package]
name = "sonnietechnologyllc/librepair-admin"
version = "0.1.6"
description = "LibRepair Super Admin Panel"
entrypoint = "server"

[dependencies]
"wasmer/static-web-server" = "=1"

[fs]
"/public" = "./dist"

[[command]]
name = "server"
module = "wasmer/static-web-server:webserver"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "wasmer/static-web-server:webserver"
main-args = ["-a", "0.0.0.0", "-p", "3000", "--root", "/public", "--page404", "/public/index.html"]
